name: bot_test
version: 0.1.3
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of general test libraries for Dart
homepage: https://github.com/kevmoo/bot_test.dart
documentation: http://kevmoo.github.io/bot_test.dart
environment:
  sdk: '>=0.8.7'
dependencies:
  bot: '>=0.24.0'
  unittest: '>=0.8.7'
dev_dependencies:
  browser: '>=0.8.7'
  hop: '>=0.26.0'
  path: '>=0.8.7'
