name: bot_test
version: 0.1.6
author: Kevin Moore <github@j832.com>
description: A collection of general test libraries for Dart
homepage: https://github.com/kevmoo/bot_test.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
documentation: http://kevmoo.github.io/bot_test.dart
dependencies:
  bot: '>=0.25.3 <0.28.0'
  unittest: '>=0.10.0 <0.12.0'
dev_dependencies:
  browser: '>=0.9.0 <0.11.0'
  hop: '>=0.30.0 <0.31.0'
  hop_docgen: '>=0.1.1 <0.2.0'
  path: '>=0.9.0 <2.0.0'
