name: bot_test
version: 0.1.5+1
author: Kevin Moore <github@j832.com>
description: A collection of general test libraries for Dart
homepage: https://github.com/kevmoo/bot_test.dart
documentation: http://kevmoo.github.io/bot_test.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bot: '>=0.25.3'
  unittest: '>=0.9.0 <0.11.0'
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  hop: '>=0.28.1+2'
  path: '>=0.9.0 <2.0.0'
