name: bot_test
version: 0.1.0
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of general test libraries for Dart
homepage: https://github.com/kevmoo/bot_test.dart
documentation: http://kevmoo.github.io/bot_test.dart
environment:
  sdk: '>=0.6.9'
dependencies:
  bot: '>=0.22.2'
  meta: '>=0.6.9'
  unittest: '>=0.6.9'
dev_dependencies:
  browser: '>=0.6.9'
  hop: '>=0.24.0'
  html5lib: '>=0.4.4'
  path: '>=0.6.9'
